site_name: POKEDEX
repo_url: https://github.com/MuriloCSeidenstucker/pokedex
repo_name: pokedex
edit_uri: tree/main/docs

theme:
  name: material
  language: pt-BR
  # logo: assets/logo.png
  # favicon: assets/logo.png

markdown_extensions:
  - attr_list

extra_css:
  - stylesheets/extra.css

nav:
  - Início: index.md
  - Visão Geral: project_overview.md
  - Instalação: installation.md
  - Uso da CLI: cli_usage.md
  - Validações: validations.md
  - Arquitetura: architecture.md
  - Exceções e Erros: exceptions.md
